### PR TITLE
Connect SearchField and GraphView

### PR DESCRIPTION
**Pull request by wowry**
**Reference Issues/PRs**
#54, #62 

**Changes**
- Change `isMain` key type to string in JSON format
- Update type handling related to JSON format in frontend (especially in `SearchField`)
  - Add `./frontend/src/types/global.d.ts`
  - Add `./frontend/src/components` dir and move component files into it
- Update GraphView props and connect it to SearchField
- Update SearchField and GraphView to support node click events (changing the main node)

### CODE REVIEW

**Comment by wowry** [comment]
Sorry, I forgot to update `handleNodeClick()`.

**Comment by ani-hovhannisyan** [comment]
That's the second case so no worries. If search flow works fine it should be easy to handle.

**Comment by wowry** [comment]
OK, changing the main node by clicking nodes is now supported.

**Comment by teruto725** [comment]
@wowry 
I got a error on your branch do you know something about that?

**Comment by wowry** [comment]
@teruto725 
Is this using Docker?
If so, could you try `. /rebuild-up.sh`?

**Comment by wowry** [comment]
@teruto725 
This error occurs because the backend has not been updated.

**Comment by teruto725** [comment]
Ok, I'll check it

**Comment by wowry** [comment]
@teruto725 
I'd like to bundle the current PRs into `develop` branch and make sure that this error disappears there.

**Comment by wowry** [comment]
@teruto725 
Do you have any other comments?
If there are none, I'd like to merge this PR into develop before merging into main.

**Comment by wowry** [comment]
Speaking of which, I removed the search button to simplify the second flow when switching the main node.

**Pull request merged**
