### PR TITLE
Create a sample graph for the graph view

### PR DESCRIPTION
**Pull request by wowry**
**Reference Issues/ PRs**
#49 

**Changes**
- Create a sample graph for the GraphView component using [react-force-graph](https://github.com/vasturiano/react-force-graph).
image
- Add a basic snapshot test that checks only the first rendering.

### CODE REVIEW

**Comment by wowry** [comment]
I'm not sure about this CI error...

**Comment by ani-hovhannisyan** [comment]
@wowry  Thanks a lot for your efforts. The looks fine. I got this promisging view: 
https://docs.google.com/document/d/1q9L0y9OQzgb0q9xUPpt3rnvNsbCtOJyu7gly8lK9lgk/edit# (last page)
However, I have some comments about coding. If it's OK and you have enough time you can change them. But I will merge this anyway, to allow future development for other members too. Also, it is better to merge in develop branch all the developed features, and once we test all of them, then to merge to main (master, I don't know hwy we have no master but main instead) branch. 
I follow KPT Problem of not reviewing code, so will add code review comments here:

**We have to follow this:**
 - All the comments should have enough explanation about what code is committed. Because imagine later you want to fix feature which was pushed and produced critical bug. How can you distinguish which commit was it? Of course, in this small project where everyone has it's task and we don't change the tasks often, you will easily find that code change, but imagine I have to fix something from graphview, at that time it will be great if only looking at "git log" I can find the possible bad committed code, or at least to find possible 3-4 commits rather than 30-40. So later please explain what is fixed? where? to which is it related? and if there's related issue put the number like this #50 in the comment message. In this case all these commits are related to 50#. You can freely use Japanese when writing the commits better Japanese than nothing )))).
 - We should skip adding console.logs in the client side if it's not related to user's question. In the main branch version to reduce such lines shall we grep and find all the lines with console.log, then to delete? No, it will take time from you, but you can comment them when committing, or use git add -p not to stage these lines, but will keep then on your side.

Some comments which are **nice to have and good to do** in later development:
1. File: App.tsx,
 - as we have many views, you can create ./view and put all view files there.
 - as far as I know, when returning some data, for later debugging and probably fixing issues, it will be easy if you define some local variable which has the data of html elements, then to return that one, in this case the div with GraphView tag.

2. File: GraphView.tsx
 - the return contains too much information without any code comments, like what is going to happen there, and as it's exceeding usual 45 lines you definitely should add comment like this: "// Setting up the coordinates of nodes... bla bla bla  // is considereg as central main node..." ))). There are empy lines which you used to separate the lines with it's logic, I guess, then you can use comments too about what is going to happen.
 - there's steps for defining style for ctx , can't it be placed in css file? To add color hash right in the code isn't good practice, if I want to change it, should I go through copy/pasting the color hex "#2196f3" "#3d5afe"" and grep in the whole src to find where is that style set?I guess No. That should be in the css file as custom class of main and other nodes, you can change only the class name by using toggling functions.
  However, if we still have to change the css style in the code it is OK if only if we have some logic of changing style frequently, and it should have some explanatory comment in the code. I know it's client side, but we will use minimized version during product release. So for frontend files no need to worry about having too much comments in the code.

3. SearchField.tsx
 - Please add one more empty line after 12th to separate const regexp from function. Btw, do you know, does frontend code pre-commit hooks check such things?
 - the regexp is containing Japanese characters only, which is great but if later I add English too it will be hard to realize what character is checked here, so please add a comment that this is for all Japanese KANJI characters regexp. 
 - The HandleKanjChange function does many different logics right? So please separate into functions like "check Japanese Characters only" and add all the regexp in that function, leave some place for later English support too (nice to have). I reduced other languages supports because we have no time to deal with others in PBL. 
 - Actually, there can be used one regexp instead of 3 if statements. And in general if statements should be used for logical different parts, because swich case is also possible coding.
 For only checking for 1 symbol Japanese character, something like below regexp should work, please test it if you have time, and use that test technic in tests too:
`/^[\u3000-\u303f\u3040-\u309f\u30a0-\u30ff\uff00-\uff9f\u4e00-\u9faf\u3400-\u4dbf]{1}$/`
 the ^ is beginning, and $ is end of line, 1 is count of symbol, and probably no need "mu" for multiline check, as we have one line only.
 I referred this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

3. Dependencies and imports
 - You used sample...json files which will later be removed, but it's good to have them right in the test folder even from now (you can refer them via relative path) so that we can later add tests using same logic as you did when coding feature. I may use same files when passing json format and won't grab into View folders structure. This is just a good practice probably, in a very big projects where front and back developers have less knowledge what's happening in the opposite side.
 - It looks like we have tons of dependencies but at this point our product does only drawing simple graph. Looks like there are some duplicates, or these are mostly nested for separated dependencies?
 - It's good practice to remove unused ones and when adding new one to check whether we already have those.

Note: I wasn't sure where to add this huge comment here or in the #50 issue. But I'm merging, and if you find misunderstanding let me know here. If you want I'll open new issues so we can slowly do those. And close this.

Thanks again !!!

**Comment by ani-hovhannisyan** [comment]
There is no automatic test yet, right? You've done manual right? May I open an issue?

**Comment by wowry** [comment]
Yes, the automatic test was run only for [this commit](https://github.com/ani-hovhannisyan/kanji-visualization/pull/50/commits/a0bd93d78c8a841ad8a4912c95ad2f589bd4f026), not for the latest commit.
I don't know why...

> May I open an issue?

Of course.

**Pull request merged**
